services:
  authenticationapi:
    build:
      context: .
      dockerfile: AuthenticationApi/Dockerfile
    ports:
      - "5001:80"

  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - authenticationapi

  identity:
    build:
      context: .
      dockerfile: Identity/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - gateway

  webapiandreact:
    build:
      context: .
      dockerfile: WebAPIAndReact/Dockerfile
    ports:
      - "5004:80"
    depends_on:
      - identity

networks:
  default:
    driver: bridge
