name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-authentication:
    name: Build & Push - AuthenticationApi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }} 
          username: ${{ secrets.ACR_USERNAME  }}
          password: ${{ secrets.ACR_PASSWORD  }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./AuthenticationApi
          file: ./AuthenticationApi/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/authenticationapi:latest

  build-gateway:
    name: Build & Push - Gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }} 
          username: ${{ secrets.ACR_USERNAME  }}
          password: ${{ secrets.ACR_PASSWORD  }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./Gateway
          file: ./Gateway/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/gateway:latest

  build-identity:
    name: Build & Push - Identity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }} 
          username: ${{ secrets.ACR_USERNAME  }}
          password: ${{ secrets.ACR_PASSWORD  }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./Identity
          file: ./Identity/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/identity:latest

  build-webapiandreact:
    name: Build & Push - WebAPIAndReact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }} 
          username: ${{ secrets.ACR_USERNAME  }}
          password: ${{ secrets.ACR_PASSWORD  }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./WebAPIAndReact
          file: ./WebAPIAndReact/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/webapiandreact:latest
